### ISSUE TITLE
General task view improvements

### ISSUE THREAD

**Issue by zeileis** [cran-task-views/ExtremeValue#1]
**Format:** We have converted the old XML-based task views file now to the new Markdown-based format. Please check the resulting .md file whether everything is in order or some corrections/improvements are needed. See the [corresponding documentation](https://github.com/cran-task-views/ctv/blob/main/Documentation.md) for more details.

**Update:** This would also be a good time to check the entire task whether it is up to date and correct. A write-up of the general goals and content guidelines is now summarized in the workflow for [proposing new task views](https://github.com/cran-task-views/ctv/blob/main/Proposal.md) (which was not yet available when you authored your task view). Improving your task view to conform more closely with these goals and guidelines, if necessary, would be highly appreciated.

**Co-maintainers:** In particular, we strongly encourage that all task views not only have a principal maintainer but also 1-5 co-maintainers in order to get more inspirations for extensions/improvements and share the maintenance workload. So please try to extend the list of co-maintainers, ideally also including female contributors and generally involving persons with diverse backgrounds.

**Comment by zeileis** [comment]
Christophe @dutangc, could you please have a look at the format of the task and whether everything is in order when converting with `ctv::ctv2html("ExtremeValue.md", cran = TRUE)` using a recent version of `ctv` from R-Forge? Then we could turn the project "Public" and include it in the new CRAN workflow.

An update, if necessary, would also be nice but is not as urgent. Regarding co-maintainers, Kevin is listed in the .md but has not yet joined the GitHub project.

**Comment by dutangc** [comment]
Dear Achim,
I need to update the view because the information is old and I'm a coauthor of a review on that topic with Leo Belzille.
Christophe

**Comment by zeileis** [comment]
That sounds great!

But please do the basic format checks as soon as possible so that we can turn the project public and include it in the new CRAN workflow. Otherwise the view would disappear from CRAN when we switch (hopefully next week).

**Comment by dutangc** [comment]
New update : I need some help to correctly format table!

**Comment by zeileis** [comment]
You can use GitHub-flavored Markdown for this, see: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables

I have reformatted the graphics for multivariate extreme value analysis using this so that you have an example.

**Comment by dutangc** [comment]
Thanks for the link : I'm still updating the view.

**Comment by zeileis** [comment]
Thanks, Christophe @dutangc. It would be great if we could have a first version that works soon.

**Comment by dutangc** [comment]
I have just made a new update. Yes I will finish very soon!

**Comment by dutangc** [comment]
This first version is correct for the CRAN release. Once public, I will probably update it before the summer. Christophe

**Comment by zeileis** [comment]
Sounds good, thanks, Christophe! I've turned the repository "Public" now and listed it on the main ctv page.
